name: 🐛 Bug report
description: Something isn't working as expected? Here is the right place to report.
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Please fill out each section below. This info allows me to diagnose and fix your issue as quickly as possible. 
        Before opening a new issue, please search existing issues [here](https://github.com/Keshav5339/My-Portfolio/issues).

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: dropdown
    id: responsiveness
    attributes:
      label: Is this a responsiveness issue?
      description: Does the bug only happen on specific screen sizes?
      options:
        - "No"
        - "Yes (Mobile)"
        - "Yes (Tablet)"
        - "Yes (Desktop/Large Screen)"
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please drag and drop or paste screenshots here if applicable.
    validations:
      required: false

  - type: textarea
    id: desktop-info
    attributes:
      label: Desktop Environment
      description: Please complete the following information if the bug happened on a PC/Laptop.
      value: |
        - OS: [e.g. Windows, macOS]
        - Browser: [e.g. Chrome, Firefox]
        - Version: [e.g. 120]
    validations:
      required: false

  - type: textarea
    id: mobile-info
    attributes:
      label: Smartphone Environment
      description: Please complete the following information if the bug happened on a phone.
      value: |
        - Device: [e.g. iPhone 15, Pixel 8]
        - OS: [e.g. iOS 17, Android 14]
        - Browser: [e.g. Safari, Chrome Mobile]
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
    validations:
      required: false